### ISSUE TITLE
clean_vrd_api should fail nicely

### ISSUE THREAD

**Issue by mqharris** [WraySmith/caRecall#29]
```
    # checks column types
    col_type <- df1[, grep("Type", colnames(df1))]

    # check for single row
    if (is.list(col_type)){
        col_type <- col_type[[1]]
    }
```

Was failing with non helpful comments if there was an empty response from the api call

**Comment by WraySmith** [comment]
I think we need to add better error handling to a bunch of the function calls (and as an extension ensure that unittests check that error handling)

Recommend another round like this one where we each take a file and do error handling for it .... potentially error handling and any code cleanup. Maybe after we're done with docs?
